### ISSUE TITLE
isServerSide is not picket up in gatsby

### ISSUE THREAD

**Issue by gustavpursche** [JoviDeCroock/hooked-head#8]
After your release earlier I got over-excited and wanted to try it out: https://deploy-preview-305--gu-stav.netlify.app/

Apparently none of the tags are rendered server side, which indicates that `isServerSide = typeof document === 'undefined';` is not picked up for some reason. Wondering why that could be. The gatsby team always recommends to reverse the check and do client side detection: `isClientSide = typeof window !== 'undefined'`. I don't know if this is related to the problem ...

I'll have a look at it tomorrow if @JoviDeCroock isn't faster :rocket:

**Comment by JoviDeCroock** [comment]
Hey @gustavpursche 

Is the code you used for this public? I can try and take a look, not sure if you have a plugin of some sorts to do the `toString()` part on the server side before you send down the html.

There is an existing one for [`react-helmet`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-react-helmet/src/gatsby-ssr.js) in our case we would just do `toString` and append it

**Comment by gustavpursche** [comment]
Right. For some reason I assumed it would just work out of the box 🙃

Code is here: https://github.com/gustavpursche/stav.dev/pull/305

**Comment by JoviDeCroock** [comment]
Seems to be a private repository, good luck on it though!

I've also pinged someone I know at gatsby if the `toString()` API is easily compatible with how they are doing things right now. If not I might change how that works and also provide component instances.

`toString` and `toComponent` but in theory I think `toString` is a good approach.

**Comment by gustavpursche** [comment]
> Seems to be a private repository, good luck on it though!

Ah damn. Forgot about it. Can make it public in a sec.

```js
// gatsby-ssr.js

import { toString } from 'hooked-head';

export const onRenderBody = () => {
  console.log(toString())
};
```

prints:

```js
true
{
  head: '\n        <title>undefined</title>\n        \n        \n      ',
  lang: undefined
}
{
  head: '\n        <title>undefined</title>\n        \n        \n      ',
  lang: undefined
}
{
  head: '\n        <title>undefined</title>\n        \n        \n      ',
  lang: undefined
```

So something doesn't seem quite right there.

> toString and toComponent but in theory I think toString is a good approach.

For gatsby we'd then have to create components out of the strings, but I guess that's fine.

**Comment by JoviDeCroock** [comment]
@gustavpursche I just cloned your repo and tried but `useEffect` doesn't seem to get called on the ssr render....

Adding
```
  useEffect(() => {
    console.log('I am sane');
  });
```

never pops up in my console

**Comment by gustavpursche** [comment]
@JoviDeCroock Mmh, now remember I read somewhere that `useEffect` is a no-op in Gatsby.

That would mean this approach doesn't work with Gatsby I guess ...

**Comment by JoviDeCroock** [comment]
I mean we'll have to find a way to effectively call what normally would be in an effect synchronously which is the reverse approach we are doing currently so I'm kind off thinking what the best approach would be.

Now we account for:
Child effect run
Parent effect run

Where as in a non deferred synchronous approach it would be
Parent run
Child run

If we add additional complexity for `next.js` we'll come to the conclusion that certain hooks can run multiple times with for instance [prepass](https://github.com/FormidableLabs/react-ssr-prepass) we need to hold a ref.

I just verified and the ref doesn't get lost so this would fix our issue:

```
const useTitle = () => {
  if (isServerSide && !hasMounted.current) {
    hasMounted.current = true; dispatcher.add()
  } 
  ...normalCode
}
```

**Comment by JoviDeCroock** [comment]
Put up a PR, going to think about this some more first before merging.

**Comment by JoviDeCroock** [comment]
I did notice however that even though the `title` and `meta` are hydrated on client-side they were picked up by GoogleBot
